---
- name: install php packages
  apt: pkg={{ item }} state=latest force=yes update_cache=yes
  with_items:
    - php5-fpm
    - php5-intl
    - php5-common
    - php5-curl
    - php5-dev
    - php5-xdebug
    - php5-mysql
    - php5-redis
    - php5-mcrypt

- name: activate extensions
  shell: ln -s -f /etc/php5/mods-available/mcrypt.ini /etc/php5/fpm/conf.d/mcrypt.ini &&  php5enmod php5-mcrypt
  notify: restart php-fpm

