<?php

namespace PersonBundle\Entity;

use Doctrine\ODM\OrientDB\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends Repository
{
}
